[2023-10-25T06:23:39.984+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=pionada_etl/run_id=manual__2023-10-25T06:18:25.073681+00:00/task_id=write_data_to_target_db permission to 509
[2023-10-25T06:23:39.985+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=pionada_etl/run_id=manual__2023-10-25T06:18:25.073681+00:00/task_id=write_data_to_target_db permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=pionada_etl/run_id=manual__2023-10-25T06:18:25.073681+00:00/task_id=write_data_to_target_db'
[2023-10-25T06:23:40.010+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=pionada_etl/run_id=manual__2023-10-25T06:18:25.073681+00:00/task_id=write_data_to_target_db permission to 509
[2023-10-25T06:23:40.011+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=pionada_etl/run_id=manual__2023-10-25T06:18:25.073681+00:00/task_id=write_data_to_target_db permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=pionada_etl/run_id=manual__2023-10-25T06:18:25.073681+00:00/task_id=write_data_to_target_db'
[2023-10-25T06:23:40.033+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pionada_etl.write_data_to_target_db manual__2023-10-25T06:18:25.073681+00:00 [queued]>
[2023-10-25T06:23:40.042+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pionada_etl.write_data_to_target_db manual__2023-10-25T06:18:25.073681+00:00 [queued]>
[2023-10-25T06:23:40.042+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-25T06:23:40.052+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): write_data_to_target_db> on 2023-10-25 06:18:25.073681+00:00
[2023-10-25T06:23:40.058+0000] {standard_task_runner.py:57} INFO - Started process 130 to run task
[2023-10-25T06:23:40.060+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'pionada_etl', 'write_data_to_target_db', 'manual__2023-10-25T06:18:25.073681+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/pionada_etl.py', '--cfg-path', '/tmp/tmpxzxnkv6g']
[2023-10-25T06:23:40.063+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask write_data_to_target_db
[2023-10-25T06:23:40.101+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=pionada_etl/run_id=manual__2023-10-25T06:18:25.073681+00:00/task_id=write_data_to_target_db permission to 509
[2023-10-25T06:23:40.102+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=pionada_etl/run_id=manual__2023-10-25T06:18:25.073681+00:00/task_id=write_data_to_target_db permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=pionada_etl/run_id=manual__2023-10-25T06:18:25.073681+00:00/task_id=write_data_to_target_db'
[2023-10-25T06:23:40.104+0000] {task_command.py:416} INFO - Running <TaskInstance: pionada_etl.write_data_to_target_db manual__2023-10-25T06:18:25.073681+00:00 [running]> on host 84b7c80bed96
[2023-10-25T06:23:40.310+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pionada_etl' AIRFLOW_CTX_TASK_ID='write_data_to_target_db' AIRFLOW_CTX_EXECUTION_DATE='2023-10-25T06:18:25.073681+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-25T06:18:25.073681+00:00'
[2023-10-25T06:23:42.093+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-25T06:23:42.103+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=pionada_etl, task_id=write_data_to_target_db, execution_date=20231025T061825, start_date=20231025T062340, end_date=20231025T062342
[2023-10-25T06:23:42.163+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-25T06:23:42.181+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
